### ISSUE TITLE
Random crash of client on OSX

### ISSUE THREAD

**Issue by lunokhod** [Storj/dataserv-client#126]
After running 2.1.2 on OSX for more than 24h, it finally crashed. Here's the output
~~~~
WARNING dataserv_client.messaging 47: HTTPError()
WARNING dataserv_client.messaging 56: HTTPError()
INFO dataserv_client.messaging 77: Query retry in 30 seconds.
INFO dataserv_client.messaging 42: Query: http://status.driveshare.org:5000/api/ping/1QJ6c6E21pyXbb7kCXjLsR8AqfLZF2scMH
WARNING dataserv_client.messaging 47: HTTPError()
WARNING dataserv_client.messaging 56: HTTPError()
INFO dataserv_client.messaging 77: Query retry in 30 seconds.
INFO dataserv_client.messaging 42: Query: http://status.driveshare.org:5000/api/ping/1QJ6c6E21pyXbb7kCXjLsR8AqfLZF2scMH
WARNING dataserv_client.messaging 47: HTTPError()
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/messaging.py", line 43, in _url_query
    response = urllib.request.urlopen(req)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: UNAUTHORIZED

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/messaging.py", line 43, in _url_query
    response = urllib.request.urlopen(req)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: UNAUTHORIZED

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/messaging.py", line 43, in _url_query
    response = urllib.request.urlopen(req)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dataserv-client", line 10, in <module>
    return getattr(client, command_name)(**arguments)
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/api.py", line 149, in poll
    self.ping()
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/api.py", line 132, in ping
    self.messenger.ping()
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/messaging.py", line 120, in ping
    return self._url_query("/api/ping/%s" % self.auth_address())
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/messaging.py", line 57, in _url_query
    self._handle_connection_error(api_path, retries, authenticate)
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/messaging.py", line 79, in _handle_connection_error
    return self._url_query(api_path, retries + 1, authenticate)
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/messaging.py", line 57, in _url_query
    self._handle_connection_error(api_path, retries, authenticate)
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/messaging.py", line 79, in _handle_connection_error
    return self._url_query(api_path, retries + 1, authenticate)
  File "/usr/local/lib/python3.4/site-packages/dataserv_client/messaging.py", line 59, in _url_query
    raise exceptions.ServerError(self._server_url)
dataserv_client.exceptions.ServerError: Server error at http://status.driveshare.org:5000!
~~~~

The HTTP warnings are probably due to the fact that it is impossible to synchronize my system time, being behind a firewall, and the tolerance of 15 seconds is just way too low. In any case, this is probably not the cause of the crash.

**Comment by littleskunk** [comment]
Bug confirmed but not the way you will like.

Your time is our of sync. I did the same with my pc and tryed a ping.

WARNING dataserv_client.messaging 47: HTTPError()
WARNING dataserv_client.messaging 56: HTTPError()
INFO dataserv_client.messaging 77: Query retry in 30 seconds.

401 (authentication failed) should cause no retry. Thats the bug we will fix but it will not help you.

You have to sync your clock or set it yourself as good as you can. You can try my testserver. I can see your time difference in the logs.

**Comment by littleskunk** [comment]
401 and 413 (height limit) are missing
413 has to be thrown like the other. That part is easy.

401 happens some times and has to be recovered but on the other side the recovery will fail as well if the clock is to much out of sync. I will check the query url to decide if 401 should be recovered or thrown. In case of set_height and ping it should be recovered. In case of register and /api/address it should be thrown.

**Comment by littleskunk** [comment]
Sorry i was wrong. 413 will stop immediately. No need for a fix. At the end i only repaired the log in case of 401. 

old log:
WARNING dataserv_client.messaging 47: HTTPError()
WARNING dataserv_client.messaging 56: HTTPError()
INFO dataserv_client.messaging 77: Query retry in 30 seconds.

fixed log:
WARNING dataserv_client.messaging 57: HTTP Error 401: UNAUTHORIZED
INFO dataserv_client.messaging 78: Query retry in 30 seconds.

**Comment by F483** [comment]
Internal server and auth errors are likely the result of the old slow server. Can you confirm this still persists on the now server at `http://104.236.1.59`?

**Comment by lunokhod** [comment]
I'm closing this issue as it hasn't reoccured since upgrading to 2.1.3.

**Comment by super3** [comment]
@lunokhod Glad it was solved for you.
